# Generated by Django 3.0.6 on 2020-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200523_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default='devjun0421@gmail.com', max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
